<?php

/**
 * @file
 * Contains list_grid.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function list_grid_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the list_grid module.
    case 'help.page.list_grid':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function list_grid_theme(): array {
  return [
    'list_grid' => [
      'variables' => [
        'content' => NULL,
        'links' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_views_pre_view().
 *
 * @param \Drupal\views\ViewExecutable $view
 * @param $display_id
 * @param array $args
 */
function list_grid_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  $gridList = Drupal::service('list_grid')->data();
  if ($view->id() == $gridList[0]) {
    $view->setDisplay($gridList[1]);
    $options = [
      'id' => 'entity_block',
      'table' => 'views',
      'field' => 'entity_block',
      'relationship' => 'none',
      'group_type' => 'none',
      'admin_label' => '',
      'empty' => TRUE,
      'tokenize' => TRUE,
      'target' => 'listgridblock',
      'view_mode' => 'default',
      'bypass_access' => FALSE,
      'plugin_id' => 'entity',
    ];
    $view->setHandler($gridList[1], 'header', 'entity_block', $options);
  }

}
//
///**
// * Implements hook_install().
// */
//function list_grid_install() {
//
//  $block_content = BlockContent::create([
//    'type' => 'basic',
//    'info' => 'Demo Block',
//  ]);
//  $block_content->set('body', 'This is demo block for drupal 8');
//  $block_content->save();
//
//  $block = Block::create([
//    'id' => 'default_demo_block',
//    'plugin' => 'block_content:' . $block_content->uuid(),
//    'region' => 'content',
//    'provider' => 'block_content',
//    'weight' => -100,
//    'theme' => \Drupal::config('system.theme')->get('default'),
//    'visibility' => [
//      'request_path' => [
//        'id' => 'request_path',
//        'pages' => '/demopage'
//      ]
//    ],
//    'settings' => [
//      'label' => 'Demo Block',
//      'label_display' => 'visible',
//    ],
//  ]);
//  $block->save();
//}
